/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: ChloeRobynSmith (https://sketchfab.com/chloerobyn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dobby-the-free-house-elf-harry-potter-f8217511c31946e28f9ce121b5549b5a
Title: Dobby the Free House Elf - Harry Potter
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Dobby(props) {
  const { nodes, materials } = useGLTF('/dobby/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['defaultMat.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
