/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: Heniqueish (https://sketchfab.com/Heniqueish)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/elder-wand-37cee9fb76494799b743aea2fe41fd26
Title: Elder Wand
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Elder(props) {
  const { nodes, materials } = useGLTF('/elder/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.ElderWand} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
