/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: Artur Coelho (https://sketchfab.com/coelhoelectrico)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-ford-anglia-b8dddbb9fee04ce387dcfe4fe972ed09
Title: Flying Ford Anglia
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function FordCar(props) {
  const { nodes, materials } = useGLTF('/flyingford/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
