/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 scene.gltf 
Author: Matthew Tew (https://sketchfab.com/matt1279797)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/harry-potter-9e546d0de09d4bd4b54e5f705b568769
Title: Harry Potter
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Potter(props) {
  const { nodes, materials } = useGLTF('/potter/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Harry_clothes1.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Harry_clothes2.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Harry_eyelash.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Harry_eyes.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Harry_glasses.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Harry_hair.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Harry_hands.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Harry_head.001']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Harry_lacrimal.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Harry_mouth.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['material_0.007']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['material_1.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
