/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 scene.gltf 
Author: Abdelrahman mamdouh (https://sketchfab.com/abdo.artist2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golden-snitch-harry-potter-ef6d102242004670b2974f53dc6c77a1
Title: Golden Snitch [ harry potter ]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Snitch(props) {
  const { nodes, materials } = useGLTF('/snitch/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.gold} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.DefaultMaterial} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
