/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 scene.gltf 
Author: Kate Abaeva (https://sketchfab.com/kate.petris)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/harry-potter-forms-and-details-3b48b869e5a7440fb2eb94e9bf33a303
Title: Harry Potter forms and details
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Three(props) {
  const { nodes, materials } = useGLTF('/threeitems/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.022}>
        <group position={[-617.385, 0, 542.232]}>
          <mesh geometry={nodes['Box670_Material_#2264_0'].geometry} material={materials.Material_2264} />
          <mesh geometry={nodes['Box670_Material_#2250_0'].geometry} material={materials.Material_2250} />
          <mesh geometry={nodes['Box670_Material_#2251_0'].geometry} material={materials.Material_2251} />
          <mesh geometry={nodes['Box670_Material_#2260_0'].geometry} material={materials.Material_2260} />
          <mesh geometry={nodes['Box670_Material_#2265_0'].geometry} material={materials.Material_2265} />
          <mesh geometry={nodes['Box670_Material_#2249_0'].geometry} material={materials.Material_2249} />
          <mesh geometry={nodes['Box670_Material_#2255_0'].geometry} material={materials.Material_2255} />
          <mesh geometry={nodes['Box670_Material_#2256_0'].geometry} material={materials.Material_2256} />
          <mesh geometry={nodes['Box670_Material_#2257_0'].geometry} material={materials.Material_2257} />
          <mesh geometry={nodes['Box670_Material_#2253_0'].geometry} material={materials.Material_2253} />
          <mesh geometry={nodes['Box670_Material_#2254_0'].geometry} material={materials.Material_2254} />
          <mesh geometry={nodes['Box670_Material_#2258_0'].geometry} material={materials.Material_2258} />
          <mesh geometry={nodes['Box670_Material_#2259_0'].geometry} material={materials.Material_2259} />
          <mesh geometry={nodes['Box670_Material_#489_0'].geometry} material={materials.Material_489} />
          <mesh geometry={nodes['Box670_Material_#2252_0'].geometry} material={materials.Material_2252} />
          <mesh geometry={nodes['Box670_Material_#2261_0'].geometry} material={materials.Material_2261} />
          <mesh geometry={nodes['Box670_Material_#2262_0'].geometry} material={materials.Material_2262} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
